### ISSUE TITLE
examples: helloworld-client fails to build on mac

### ISSUE THREAD

**Issue by DominicWrege** [hyperium/tonic#210]
### Version
Master

tonic-examples v0.1.0 (/private/tmp/tonic/examples)
├── tonic v0.1.0-beta.1 (/private/tmp/tonic/tonic)
└── tonic-build v0.1.0-beta.1 (/private/tmp/tonic/tonic-build)
### Platform

 
Mac OS X 10.14.6 (x86_64 Darwin 18.7.0)

#### Reproduce
Clone master, cd into examples and then run:
```export RUST_BACKTRACE=1```
```cargo run --bin helloworld-client```

#### Output

```
error: failed to run custom build command for `tonic-examples v0.1.0 (/private/tmp/tonic/examples)`

Caused by:
  process didn't exit successfully: `/private/tmp/tonic/target/debug/build/tonic-examples-481c3c4c3033d33c/build-script-build` (exit code: 101)
--- stdout
out: Output { status: ExitStatus(ExitStatus(256)), stdout: "Unrecognized option: \'emit\'\n\nusage: rustfmt [options] <file>...\n\nOptions:\n    -h, --help          show this message\n    -V, --version       show version information\n    -v, --verbose       print verbose output\n    -f, --force         force rustfmt to actually run\n        --write-mode [replace|overwrite|display|diff|coverage|checkstyle]\n                        mode to write in (not usable when piping from stdin)\n        --skip-children \n                        don\'t reformat child modules\n        --config-help   show details of rustfmt configuration options\n        --dump-default-config PATH\n                        Dumps the default configuration to a file and exits.\n        --dump-minimal-config PATH\n                        Dumps configuration options that were checked during\n                        formatting to a file.\n        --config-path [Path for the configuration file]\n                        Recursively searches the given path for the\n                        rustfmt.toml config file. If not found reverts to the\n                        input file path\n        --file-lines JSON\n                        Format specified line ranges. See README for more\n                        detail on the JSON format.\n\n", stderr: "" }

--- stderr
thread 'main' panicked at 'assertion failed: out.status.success()', tonic-build/src/lib.rs:214:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  11: __rust_probestack
  12: tonic_build::fmt
             at tonic-build/src/lib.rs:214
  13: tonic_build::Builder::compile
             at /private/tmp/tonic/tonic-build/src/lib.rs:158
  14: tonic_build::compile_protos
             at /private/tmp/tonic/tonic-build/src/lib.rs:193
  15: build_script_build::main
             at examples/build.rs:2
  16: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: std::panicking::try
             at src/libstd/panicking.rs:265
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  23: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  24: build_script_build::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by LucioFranco** [comment]
Can you ensure you have `rustfmt` installed?

**Comment by DominicWrege** [comment]
Sry i had an old version of ```rustfmt```installed
