### ISSUE TITLE
failed to compile proto file using tonic-build

### ISSUE THREAD

**Issue by alonlong** [hyperium/tonic#518]
**Cargo.toml**

```
[package]
name = "rocket-rust"
version = "0.1.0"
authors = ["alonlong <alonlong@163.com>"]
edition = "2018"

[dependencies]
tonic = "0.3.0"
prost = "0.6.0"

[build-dependencies]
tonic-build = "0.3.0"
```

**greeter.proto**
```
syntax = "proto3";

package greeter;

service GreeterService {
    rpc Say (SayRequest) returns (SayResponse);
}

message SayRequest {
    string name = 1;
}

message SayResponse {
    string message = 1;
}
```

**build.rs**
```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::compile_protos("proto/greeter.proto")?;
    Ok(())
}
```

**when i try the command: cargo build, it happens an error like this:** 

```
$ cargo build
   Compiling rocket-rust v0.1.0 (~/rocket-rust)
error: failed to run custom build command for `rocket-rust v0.1.0 (~/rocket-rust)`

Caused by:
  process didn't exit successfully: `~/rocket-rust/target/debug/build/rocket-rust-3d86180411ea18ed/build-script-build` (exit code: 1)
```

**call stack**
```
$ RUST_BACKTRACE=1 ./build-script-build
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /Users/longwu/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tonic-build-0.3.1/src/prost.rs:283:52
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e2267046859c9ceb932abc983561d53a117089f6/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/e2267046859c9ceb932abc983561d53a117089f6/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/e2267046859c9ceb932abc983561d53a117089f6/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e2267046859c9ceb932abc983561d53a117089f6/library/core/src/result.rs:973:23
   4: tonic_build::prost::Builder::compile_with_config
             at /Users/longwu/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tonic-build-0.3.1/src/prost.rs:283:27
   5: tonic_build::prost::Builder::compile
             at /Users/longwu/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tonic-build-0.3.1/src/prost.rs:266:9
   6: tonic_build::prost::compile_protos
             at /Users/longwu/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tonic-build-0.3.1/src/prost.rs:37:5
   7: build_script_build::main
             at /Users/longwu/Project/rust/tonic-rust/build.rs:2:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/e2267046859c9ceb932abc983561d53a117089f6/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by alonlong** [comment]
the compiling works well when using "proto-rust-grpc" way

**Comment by davidpdrsn** [comment]
I've tested this on 0.4 and it works for me.

Are you still having issues?

**Comment by alonlong** [comment]
> I've tested this on 0.4 and it works for me.
> 
> Are you still having issues?

Yes

**Comment by davidpdrsn** [comment]
Does updating to 0.4 not fix it? If not would you make a repo that reproduces it that I can download?

**Comment by davidpdrsn** [comment]
Could this because `rustfmt` isn't installed and on your `$PATH`? @alonlong are you able to give https://github.com/hyperium/tonic/pull/621 a try?
